M48
; DRILL file {KiCad 7.0.5} date Sun Feb 25 22:17:51 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-02-25T22:17:51+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X79.029Y-22.205
X84.809Y-22.205
T2
X60.25Y-19.75
X60.25Y-56.75
X101.75Y-19.75
X101.75Y-56.75
T0
M30
